### ISSUE TITLE
Design: Move to New Organization

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-web#50]
Occasionally a person will be invited to an existing organization when they should have registered a new organization. If not fixed, then that person invites dozens of other workers, who then invite others, etc. They claim and create cases. Then later they want to move the entire tree over to a new organization due to the original mistake.
Also, sometimes volunteers switch organizations between incidents.
This feature allows a person to move him/herself and optionally his/her entire tree to another existing organization, or an entirely new organization. See "EXAMPLE LIST BELONGING TO AARON TITUS" in Issue #40 for some interface requirements.

- [ ] Place this functionality in User Settings: Move Organizations
- [ ] **STEP 1**: "To where do you want to move?" [Existing Organization] [New Organization]
  - [ ] If Existing Organization, then prompt the user to enter the email address of someone in that organization.
    - [ ] Go to STEP 2, then follow the steps in Issue #34, except the user does not need to register or choose a new password.
  - [ ] If New Organization, then prompt the user to immediately register a new organization, and go to STEP 2.

- [ ] **STEP 2**: "Who do you want to move to [$Target/New Organization]?"
  - [ ] Create a cascading list of other users the current user invited.
  - [ ] Create options in "EXAMPLE LIST BELONGING TO AARON TITUS" in Issue #40
  - [ ] Follow steps in Issue #40 

Design for the following Formats:
- [ ] Desktop
- [ ] Tablet
- [ ] Smartphone
- [ ] App
Final Output
- [ ] Wireframe or PSD
