### ISSUE TITLE
Design: Activate Special Modules

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-web#64]
Create an easy way for users to activate any/all of the following modules:
- [ ] Helpdesk Support Agent Module (See Issue #57 )
- [ ] Advanced Mapping Module (See Issue #61 )
- [ ] Phone Agent Module (See Issue #55 )
- [ ] Translation Module (See Issue #39 )
- [ ] Any other module created in the future

Some modules will automatically appear depending on the user's role. For example:
- [ ] Affiliate Organizations Module: Appears if user is a Primary Contact

- [ ] If a module requires a higher-level role, then the user is directed to Switch Roles, which may require approval from someone else in the organization.

Design for the following Formats:
- [ ] Desktop
- [ ] Tablet
- [ ] Smartphone
- [ ] App
Final Output
- [ ] Wireframe or PSD
